name: CI (example)

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  ubuntu-ci:
    name: Spectral ubuntu CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: ChengaDev/spectral-extended-github-action@v1.0
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          spectral-args: scan --ok
  ubuntu-audit:
    name: Spectral ubuntu audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral Audit
        uses: ChengaDev/spectral-extended-github-action@v1.0
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          spectral-args: github -k repo -t ${{ secrets.MY_GITHUB_TOKEN }} https://github.com/ChengaDev/spectral-extended-github-action --include-tags base,audit --ok
  macos-ci:
    name: Spectral macos CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: ChengaDev/spectral-extended-github-action@v1.0
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          spectral-args: scan --ok
  macos-audit:
    name: Spectral macos audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral Audit
        uses: ChengaDev/spectral-extended-github-action@v1.0
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          spectral-args: github -k repo -t ${{ secrets.MY_GITHUB_TOKEN }} https://github.com/ChengaDev/spectral-extended-github-action --include-tags base,audit --ok
  # windows-ci:
  #   name: Spectral windows CI
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install and run Spectral CI
  #       uses: ChengaDev/spectral-extended-github-action@v1.0
  #       with:
  #         spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
  #         spectral-args: scan --ok
  # windows-audit:
  #   name: Spectral windows audit
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install and run Spectral Audit
  #       uses: ChengaDev/spectral-extended-github-action@v1.0
  #       with:
  #         spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
  #         spectral-args: github -k repo -t ${{ secrets.MY_GITHUB_TOKEN }} https://github.com/ChengaDev/spectral-extended-github-action --include-tags base,audit --ok
